import { GlobalThemeOverrides } from "naive-ui";
import "./index.scss";
import "./theme.scss";

export const themeLightOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: "rgba(80, 120, 200, 1)",
    primaryColorHover: "rgba(80, 120, 200, 1)"
  }
};
export const themeDarkOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: "rgba(80, 120, 200, 1)",
    primaryColorHover: "rgba(80, 120, 200, 1)"
  }
  // common: {
  //   primaryColor: "rgba(80, 120, 200, 1)",
  //   primaryColorHover: "rgba(80, 120, 200, 1)"
  // }
};
const common: any = {
  fontFamily: "",
  fontFamilyMono: "",
  fontWeight: "",
  fontWeightStrong: "",
  cubicBezierEaseInOut: "",
  cubicBezierEaseOut: "",
  cubicBezierEaseIn: "",
  borderRadius: "",
  borderRadiusSmall: "",
  fontSize: "",
  fontSizeMini: "",
  fontSizeTiny: "",
  fontSizeSmall: "",
  fontSizeMedium: "",
  fontSizeLarge: "",
  fontSizeHuge: "",
  lineHeight: "",
  heightMini: "",
  heightTiny: "",
  heightSmall: "",
  heightMedium: "",
  heightLarge: "",
  heightHuge: "",
  baseColor: "",
  primaryColor: "",
  primaryColorHover: "",
  primaryColorPressed: "",
  primaryColorSuppl: "",
  infoColor: "",
  infoColorHover: "",
  infoColorPressed: "",
  infoColorSuppl: "",
  successColor: "",
  successColorHover: "",
  successColorPressed: "",
  successColorSuppl: "",
  warningColor: "",
  warningColorHover: "",
  warningColorPressed: "",
  warningColorSuppl: "",
  errorColor: "",
  errorColorHover: "",
  errorColorPressed: "",
  errorColorSuppl: "",
  textColorBase: "",
  textColor1: "",
  textColor2: "",
  textColor3: "",
  textColorDisabled: "",
  placeholderColor: "",
  placeholderColorDisabled: "",
  iconColor: "",
  iconColorHover: "",
  iconColorPressed: "",
  iconColorDisabled: "",
  opacity1: "",
  opacity2: "",
  opacity3: "",
  opacity4: "",
  opacity5: "",
  dividerColor: "",
  borderColor: "",
  closeIconColor: "",
  closeIconColorHover: "",
  closeIconColorPressed: "",
  closeColorHover: "",
  closeColorPressed: "",
  clearColor: "",
  clearColorHover: "",
  clearColorPressed: "",
  scrollbarColor: "",
  scrollbarColorHover: "",
  scrollbarWidth: "",
  scrollbarHeight: "",
  scrollbarBorderRadius: "",
  progressRailColor: "",
  railColor: "",
  popoverColor: "",
  tableColor: "",
  cardColor: "",
  modalColor: "",
  bodyColor: "",
  tagColor: "",
  avatarColor: "",
  invertedColor: "",
  inputColor: "",
  codeColor: "",
  tabColor: "",
  actionColor: "",
  tableHeaderColor: "",
  hoverColor: "",
  tableColorHover: "",
  tableColorStriped: "",
  pressedColor: "",
  opacityDisabled: "",
  inputColorDisabled: "",
  buttonColor2: "",
  buttonColor2Hover: "",
  buttonColor2Pressed: "",
  boxShadow1: "",
  boxShadow2: "",
  boxShadow3: ""
};
